### ISSUE TITLE
Add StyleCI Support

### ISSUE THREAD

**Issue by vinkla** [pusher/pusher-http-php#72]
What about adding https://styleci.io/ support? Then we will get syntax checks on all commits and PRs made to this repository.

This is the guide to add StyleCI support:

1. Sign up at https://styleci.io/
2. Go to the repositories page https://styleci.io/account#repos
3. Enable this repository.
4. Press **Show Analysis** and then **Settings**.
5. Add the following settings:
    ```yml
    enabled:
      - unalign_double_arrow

    disabled:
      - psr0
      - align_double_arrow
      - phpdoc_align
    ```
6. Press **Save Configuration**.
7. Press **Analyze Now**. 

This has to be done by the owner of the repository.

**Comment by GrahamCampbell** [comment]
Technically clicking the 2nd link will signup you up and return you there. :)

**Comment by vinkla** [comment]
Thats true :)

**Comment by tanuck** [comment]
:+1:

**Comment by zimbatm** [comment]
Isn't psr0 desirable ?

**Comment by GrahamCampbell** [comment]
> Isn't psr0 desirable ?

No. PSR-4 is the new standard.

That config sample provided was old anyway though. We no longer have the psr0 fixer enabled in the presets. psr4 is enabled by default.

**Comment by zimbatm** [comment]
Thanks, I'm impressed, the service is pretty cool.

Here is the config that I'm using for now:
```yaml
enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - phpdoc_align
  - short_array_syntax
```
